// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXJuUbOBx2BiGkA2MaHxF6J_htrahGbYI',
    appId: '1:288539642893:web:482b3a44baf49788d99944',
    messagingSenderId: '288539642893',
    projectId: 'thread-25',
    authDomain: 'thread-25.firebaseapp.com',
    storageBucket: 'thread-25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFBq-1pmr_mWzQwvL1HOEov7zPW5CRvo',
    appId: '1:288539642893:android:fae7cdb934a78894d99944',
    messagingSenderId: '288539642893',
    projectId: 'thread-25',
    storageBucket: 'thread-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKshlxnwlVnunj8OopuuTDrJ3z3wg-hjE',
    appId: '1:288539642893:ios:045fea6297aae4c8d99944',
    messagingSenderId: '288539642893',
    projectId: 'thread-25',
    storageBucket: 'thread-25.firebasestorage.app',
    iosBundleId: 'com.example.threads',
  );

}